import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  clashDisplay,
  zodiakVariable,
  zodiakVariableItalic,
  montserratVariable,
} from './fonts/font';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${clashDisplay.variable} ${zodiakVariable.variable} ${zodiakVariableItalic.variable} ${montserratVariable.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
